### ISSUE TITLE
proposal to “merge” the concepts of ports and options

### ISSUE THREAD

**Issue by xquery** [xproc/1.0-specification#109]
http://lists.w3.org/Archives/Public/public-xml-processing-model-comments/2014Feb/0001.html

'TL;DR: A proposal to “merge” the concepts of ports and options (an options == a port), while still enabling static dependency graph analysis. Based on the possibility to bind readable ports to variables available in the in-scope bindings of a step.'

Considering the vast amount of previous discussions (and assumptions) on ports and options as separate and well defined abstractions in xproc I don't think we could reasonably consider such a proposal but its got significant merit and worth a more indepth discussion.

On first read, I get the impression that we could address many of the use cases in similar ways with existing 'buckets' of work identified ... but would like to discuss at next WG.

**Comment by rdeltour** [comment]
Thanks for putting this on the table Jim. One comment: I'm aware that the port/option merger idea exposed in the thread linked above is probably too "extreme" to be considered for 2.0, but otherwise I'd like to hear your thoughts on being able to access readable ports from in-scope bindings (while still keeping options/ports separate). I've heard several times that it was more complex than it looked and would break static analysis, but I've not seen substantial proof or counter-user-cases either... so looking forward to this discussion! Lemme know if I can help or clarify anyhow.

**Comment by ndw** [comment]
Per the 08 April 2015 telcon, we're closing this issue without action.

http://www.w3.org/XML/XProc/2015/04/08-minutes#item04
