### ISSUE TITLE
2.7.10 Syntax: add an AVT @value attribute to options, parameters, and variables

### ISSUE THREAD

**Issue by ndw** [xproc/1.0-specification#43]
XProc 1.0 offers relatively few default behaviors, requiring instead that pipelines specify every construct fully. User experience has demonstrated that this leads to very verbose pipelines and has been a constant source of complaint. XProc 2.0 will introduce a variety of syntactic simplifications as an aid to readability and usability, including but not limited to:

Add an AVT value attribute to options, parameters, and variables (to be used instead of select)

**Comment by ndw** [comment]
On further reflection, I'm not sure this is a good idea. There's no parallel in XSLT, for example, and I've never heard  anyone complaining about it. Seems to me that it could be quite confusing.

**Comment by rdeltour** [comment]
If I may bring my user point of view: a place where I think AVTs would be really handy is in options _syntactic shortcut_ attributes, in order to reduce the verbosity of `p:with-option` children.

For instance:

``` xml
<p:add-attribute attribute-name="href" match="*">
    <p:input port="source">
      <p:inline>
        <c:request method="get"/>
      </p:inline>
    </p:input>
    <p:with-option name="attribute-value"
      select="concat('http://en.wiktionary.org/w/api.php?action=query&amp;titles=',
             encode-for-uri(.),
             '&amp;format=xml&amp;prop=extracts')" />
</p:add-attribute>
```

becomes

``` xml
<p:add-attribute attribute-name="href" match="*" attribute-value="http://en.wiktionary.org/w/api.php?action=query&amp;titles={encode-for-uri(.)}&amp;format=xml&amp;prop=extracts">
  <p:input port="source">
    <c:request method="get"/>
  </p:input>
</p:add-attribute>
```

(ok, I cheat by using the inline syntax shortcut already ;)

Of course, the real issue there is that you lose backward compatibility with XProc 1.0...

Otherwise, for `p:variable` or `p:with-option`, I agree that an AVT attribute wouldn't bring a lot to the existing `select` attributes (especially thx to the new XPath 3.0 concat operator) and would be more confusing than useful. As for parameters it basically depends on how they're handled in 2.0.

**Comment by ndw** [comment]
There's no question of doing AVTs in shortcut options (and possibly other places). There's a separate issue for that, #33. That's absolutely required. This issue is really just about a `value` attribute parallel to `select` and I find I don't have much enthusiasm for it.

**Comment by rdeltour** [comment]
> There's no question of doing AVTs in shortcut options (and possibly other places). There's a separate issue for that, #33.

Oh, sorry I missed that one.

> This issue is really just about a value attribute parallel to select and I find I don't have much enthusiasm for it.

:+1:  Meh too

**Comment by ndw** [comment]
At the 25 March telcon, we decided to close this issue without action. http://www.w3.org/XML/XProc/2015/03/25-minutes.html
